//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoping_Cart
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblcategory()
        {
            this.tblproducts = new HashSet<tblproduct>();
        }
    
        public int cid { get; set; }
        public string cname { get; set; }
    
        public virtual tblcategory tblcategory1 { get; set; }
        public virtual tblcategory tblcategory2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblproduct> tblproducts { get; set; }
    }
}
